# Generated by Django 5.2.1 on 2025-06-03 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='dealer',
            new_name='dealership',
        ),
    ]
