# Generated by Django 5.2.1 on 2025-06-03 01:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0003_alter_review_car'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carmodel',
            old_name='dealer_id',
            new_name='mileage',
        ),
        migrations.AddField(
            model_name='carmodel',
            name='body_type',
            field=models.CharField(default='Unknown', max_length=50),
        ),
        migrations.AddField(
            model_name='carmodel',
            name='dealer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='djangoapp.dealer'),
        ),
    ]
